BUG: setJobsAndPoses、DEBUG: loadText
stdout | tests/isJobIncludesKeyword.test.js > test
rate
weight
排序工作

 ✓ tests/isJobIncludesKeyword.test.js (1 test) 968ms
   ✓ test  967ms
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot set property _items of #<Object> which has only a getter
 ❯ Finder.onError node_modules/@asamuzakjp/dom-selector/dist/cjs/index.cjs:1657:13
 ❯ DOMSelector.querySelectorAll node_modules/@asamuzakjp/dom-selector/dist/cjs/index.cjs:4600:20
 ❯ HTMLDivElementImpl.querySelectorAll node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:78:31
 ❯ HTMLDivElement.querySelectorAll node_modules/jsdom/lib/jsdom/living/generated/Element.js:1119:58
 ❯ setJobsAndPoses src/js/mobile/setJobsAndPoses.js:8:25
      6| // 預設`jobHrefs`為全部資料、如果`jobEls`非空會從中抓取`<a>`的`href`屬性
      7| function setJobsAndPoses(jobsView) {
      8|   let jobEls = jobsView.querySelectorAll('.job')
       |                         ^
      9|   let jobHrefs = jobEls
     10|     ? jobEls.map(el => el.querySelector('a').getAttribute('href'))
 ❯ Object.updated src/js/mobile/setJobsAndPoses.js:17:3
 ❯ Proxy.updated src/components/results/KeywordCoverageResult.vue:250:21
 ❯ node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3038:40
 ❯ callWithErrorHandling node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:200:19
 ❯ callWithAsyncErrorHandling node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:207:17

This error originated in "tests/isJobIncludesKeyword.test.js" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "test". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.
Caused by: TypeError: Cannot set property _items of #<Object> which has only a getter
 ❯ new OrderedSet node_modules/jsdom/lib/jsdom/living/helpers/ordered-set.js:10:17
 ❯ new DOMTokenListImpl node_modules/jsdom/lib/jsdom/living/nodes/DOMTokenList-impl.js:32:22
 ❯ Object.exports.setup node_modules/jsdom/lib/jsdom/living/generated/DOMTokenList.js:65:12
 ❯ Object.exports.create node_modules/jsdom/lib/jsdom/living/generated/DOMTokenList.js:50:18
 ❯ Object.exports.createImpl node_modules/jsdom/lib/jsdom/living/generated/DOMTokenList.js:54:27
 ❯ HTMLDivElementImpl.get classList [as classList] node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:201:38
 ❯ node_modules/jsdom/lib/jsdom/living/generated/Element.js:1252:59
 ❯ Object.getSameObject node_modules/jsdom/lib/jsdom/living/generated/utils.js:74:37
 ❯ HTMLDivElement.get classList [as classList] node_modules/jsdom/lib/jsdom/living/generated/Element.js:1251:20
 ❯ Finder._matchSelectorForElement node_modules/@asamuzakjp/dom-selector/dist/cjs/index.cjs:3168:18

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯